language: android
jdk: openjdk7
android:
  components:
    - build-tools-20.0.0
    - extra-android-m2repository
    - android-L
  licenses:
    - '.+'
before_install:
 - chmod +x gradlew
script:
  - ./gradlew check

