language: android
jdk: oraclejdk7
android:
  components:
    - build-tools-23.0.2
    - android-23
    - extra-android-m2repository
    - extra-google-m2repository
  licenses:
    - '.+'
before_install:
 - chmod +x gradlew
script:
  - ./gradlew check

